#!/usr/bin/env python3
"""Stealth-mode guard (active only when stealth-mode.value == "on").

PreToolUse Bash hook. NO-OP unless `.claude/grimoire-config.json` has
`stealth-mode.value == "on"` — so it adds zero behavioural change (and the
cheapest possible exit) for the common, stealth-off case.

When Stealth Mode IS on, it enforces — fail-closed — the four artifact rails
from docs/design/stealth-mode-design.md §6/§10:

  1. NO PUSH.  Every `git push` is denied (a strict superset of push-guard.sh;
     in stealth even the marker-blessed integration worktree may not push —
     the human pushes manually, outside Grimoire, if they choose).
  2. NO COMMITTING MANAGED PATHS.  `git add` / `stage` / `rm` / `mv` / `commit`
     naming a Grimoire-managed path (`.claude/`, `CLAUDE.md`, design docs, …) is
     denied, so the framework's own files never reach a commit.
  3. COMMIT-MESSAGE HYGIENE.  `git commit -m/--message/-F/--file` whose message
     contains an AI/agent tell (claude / anthropic / Co-Authored-By / LLM / 🤖 …)
     is denied.
  4. NO GRIMOIRE BRANCH MODEL.  Creating a `version/*` branch (or `dev`/`main`
     when absent) via `switch -c` / `checkout -b` / `branch <name>` is denied —
     the branch model is itself a fingerprint; mirror the host repo instead.

Escape hatches (`--abort` / `--quit` / `--skip`) and detached HEAD / non-repo
are no-ops. Run with `--self-test` for the parser harness.
"""
import json
import os
import re
import shlex
import subprocess
import sys

# ── Deny-list (commit-message hygiene); mirrors stealth_scrub.py ───────────
_WORD_TOKENS = ["claude", "anthropic", "openai", "gpt", "copilot", "llm",
                "ai-generated", "ai generated", "assistant-generated"]
_PHRASES = [r"generated by ai", r"language model", r"co-authored-by",
            r"as an ai", r"i'm an ai", r"i am an ai"]
_LITERALS = ["🤖"]


def build_denylist_pattern(extra):
    parts = []
    for tok in _WORD_TOKENS + list(extra or []):
        parts.append(rf"(?<![A-Za-z0-9]){re.escape(tok)}(?![A-Za-z0-9])")
    for ph in _PHRASES:
        parts.append(ph.replace(" ", r"\s+"))
    for lit in _LITERALS:
        parts.append(re.escape(lit))
    return re.compile("|".join(parts), re.IGNORECASE)


# ── Managed-path default set (Grimoire's own concealed files) ──────────────
DEFAULT_MANAGED = (
    ".claude/", "CLAUDE.md", "AGENTS.md",
    "docs/design/", "docs/roadmap.md", "docs/version-history.md",
    "docs/release-planning-v", "docs/integration-workflow.md",
    "docs/coding-standards", "docs/architecture-guidelines.md",
    ".github/prompts/", ".github/copilot-instructions.md",
)

STATEMENT_SEPARATORS = {";", ";;", "&&", "||", "|", "|&", "&", "(", ")", "\n"}
OPTS_WITH_VALUE = {"-C", "--git-dir", "--work-tree", "--namespace", "-c"}
# commit options that consume a following token as their value
COMMIT_VALUE_OPTS = {"-m", "--message", "-F", "--file", "-C", "--reuse-message",
                     "-c", "--reedit-message", "--author", "--date", "-S", "--gpg-sign"}
MESSAGE_OPTS = {"-m", "--message"}
FILE_OPTS = {"-F", "--file"}
ESCAPE_HATCH = {"--abort", "--quit", "--skip", "--continue"}
BRANCH_DELETE_OR_LIST = {"-d", "-D", "--delete", "--list", "-l", "-m", "-M",
                         "--move", "-a", "--all", "-r", "--remotes", "--show-current",
                         "--edit-description", "-v", "-vv", "--merged", "--no-merged"}


def deny(msg):
    sys.stderr.write("stealth-guard: " + msg)
    sys.exit(2)


def stealth_on(proj):
    try:
        cfg = json.load(open(os.path.join(proj, ".claude", "grimoire-config.json")))
    except Exception:
        return False, []
    sm = cfg.get("stealth-mode")
    if not isinstance(sm, dict):
        return False, []
    on = (sm.get("value") == "on")
    extra = sm.get("comment-denylist", []) or []
    return on, extra


def managed_globs(proj):
    try:
        cfg = json.load(open(os.path.join(proj, ".claude", "grimoire-config.json")))
        ov = cfg.get("stealth-mode", {}).get("managed-paths")
        if ov:
            return tuple(g.lstrip("/").rstrip("*") for g in ov)
    except Exception:
        pass
    return DEFAULT_MANAGED


def is_managed(path, globs):
    p = path[2:] if path.startswith("./") else path
    p = p.lstrip("/")  # strip leading slashes only, never the dot of ".claude"
    return any(p == m or p.startswith(m) for m in globs)


def tokenize(text):
    lex = shlex.shlex(text, posix=True, punctuation_chars=True)
    lex.whitespace_split = True
    lex.commenters = "#"
    return list(lex)


def git_calls(tokens):
    """Yield (subcommand, arg_tokens) for each `git <sub> ...` simple command."""
    calls = []
    i, n = 0, len(tokens)
    while i < n:
        if tokens[i] == "git" or tokens[i].endswith("/git"):
            j = i + 1
            sub = None
            while j < n:
                t = tokens[j]
                if t in OPTS_WITH_VALUE:
                    j += 2
                    continue
                if t.startswith("-"):
                    j += 1
                    continue
                sub = t
                j += 1
                break
            args = []
            while j < n and tokens[j] not in STATEMENT_SEPARATORS:
                args.append(tokens[j])
                j += 1
            if sub:
                calls.append((sub, args))
            i = j
        else:
            i += 1
    return calls


def split_paths_and_messages(args):
    """For add/rm/mv/commit: return (positional_paths, message_strings)."""
    paths, messages = [], []
    i, n = 0, len(args)
    saw_ddash = False
    while i < n:
        t = args[i]
        if t == "--":
            saw_ddash = True
            i += 1
            continue
        if not saw_ddash and t.startswith("-"):
            # joined value form: -m=msg / --message=msg / -mMSG
            if "=" in t and t.split("=", 1)[0] in (MESSAGE_OPTS | FILE_OPTS):
                opt, val = t.split("=", 1)
                if opt in MESSAGE_OPTS:
                    messages.append(val)
                i += 1
                continue
            if t.startswith("-m") and len(t) > 2 and not t.startswith("--"):
                messages.append(t[2:])  # -mMESSAGE glued
                i += 1
                continue
            if t in MESSAGE_OPTS and i + 1 < n:
                messages.append(args[i + 1])
                i += 2
                continue
            if t in COMMIT_VALUE_OPTS and i + 1 < n:
                i += 2
                continue
            i += 1
            continue
        paths.append(t)
        i += 1
    return paths, messages


def branch_exists(proj, name):
    try:
        r = subprocess.run(["git", "-C", proj, "rev-parse", "--verify", "--quiet",
                            "refs/heads/" + name], capture_output=True, timeout=5)
        return r.returncode == 0
    except (OSError, subprocess.SubprocessError):
        return False


def created_branch_name(sub, args):
    """Return a newly-created branch name for switch -c / checkout -b / branch X."""
    if sub == "switch":
        for i, t in enumerate(args):
            if t in ("-c", "-C", "--create", "--force-create") and i + 1 < len(args):
                return args[i + 1]
            if t.startswith("-c") and len(t) > 2 and not t.startswith("--"):
                return t[2:]
        return None
    if sub == "checkout":
        for i, t in enumerate(args):
            if t in ("-b", "-B") and i + 1 < len(args):
                return args[i + 1]
        return None
    if sub == "branch":
        if any(a in BRANCH_DELETE_OR_LIST for a in args):
            return None
        for t in args:
            if not t.startswith("-"):
                return t
        return None
    return None


def check_branch(proj, sub, args):
    name = created_branch_name(sub, args)
    if not name:
        return
    if name.startswith("version/"):
        deny(f"blocked creating `{name}` — the Grimoire `version/*` branch model is\n"
             "a fingerprint and is suppressed in Stealth Mode. Work on the host\n"
             "repo's current branch, or a short-lived branch named to its own\n"
             "convention, and reconcile it before the session ends.\n")
    if name in ("dev", "main") and not branch_exists(proj, name):
        deny(f"blocked creating a new `{name}` branch in Stealth Mode — the\n"
             "Grimoire branch model is suppressed. Mirror the host repo instead.\n")


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        sys.exit(0)
    if payload.get("tool_name", "") != "Bash":
        sys.exit(0)
    proj = os.environ.get("CLAUDE_PROJECT_DIR", "")
    if not proj:
        sys.exit(0)
    on, extra = stealth_on(proj)
    if not on:
        sys.exit(0)  # ← stealth off: pure no-op, no behavioural change

    cmd = (payload.get("tool_input", {}) or {}).get("command", "") or ""
    try:
        tokens = tokenize(cmd)
    except ValueError:
        # Unparseable (e.g. unbalanced heredoc quote): fail safe on the cheap
        # high-value check — any literal `git push` denies.
        if re.search(r"\bgit\b[^\n;|&]*\bpush\b", cmd):
            deny("blocked `git push` — Stealth Mode never pushes.\n")
        sys.exit(0)

    globs = managed_globs(proj)
    denylist = build_denylist_pattern(extra)

    for sub, args in git_calls(tokens):
        if any(a in ESCAPE_HATCH for a in args):
            continue  # never trap a recovery
        if sub in ("push", "send-pack"):
            deny("blocked `git push` — Stealth Mode never pushes (categorical;\n"
                 "even the integration worktree). If you truly mean to publish,\n"
                 "disable Stealth Mode and push manually outside Grimoire.\n")
        if sub in ("switch", "checkout", "branch"):
            check_branch(proj, sub, args)
        if sub in ("add", "stage", "rm", "mv", "commit"):
            paths, messages = split_paths_and_messages(args)
            for p in paths:
                if is_managed(p, globs):
                    deny(f"blocked `git {sub} {p}` — `{p}` is a Grimoire-managed\n"
                         "path and must never be committed in Stealth Mode (it is the\n"
                         "tell). These files are excluded locally; keep them uncommitted.\n")
            for m in messages:
                hit = denylist.search(m)
                if hit:
                    deny(f"blocked `git commit` — message contains the AI/agent tell "
                         f"{hit.group(0)!r}.\nStealth Mode commit messages carry no "
                         "Claude/AI/Co-Authored-By markers. Rewrite the message.\n")
    sys.exit(0)


# ── parser self-test (no git / config needed) ──────────────────────────────
def _self_test():
    globs = DEFAULT_MANAGED
    dl = build_denylist_pattern([])

    def calls(c):
        return git_calls(tokenize(c))

    fails = 0

    def check(desc, cond):
        nonlocal fails
        print(("ok  " if cond else "FAIL") + "  " + desc)
        fails += not cond

    # push detection
    check("push detected", any(s in ("push", "send-pack") for s, _ in calls("git push origin main")))
    check("push in chain detected",
          sum(1 for s, _ in calls("git commit -m x && git push origin main") if s == "push") == 1)
    # managed path detection
    p, _ = split_paths_and_messages(calls("git add .claude/x.md")[0][1])
    check("managed add flagged", any(is_managed(x, globs) for x in p))
    p, _ = split_paths_and_messages(calls("git add src/app.py")[0][1])
    check("deliverable add not flagged", not any(is_managed(x, globs) for x in p))
    # commit message extraction + hygiene
    _, m = split_paths_and_messages(calls('git commit -m "fix: per Claude"')[0][1])
    check("msg extracted", m == ["fix: per Claude"])
    check("msg tell hit", bool(dl.search(m[0])))
    _, m2 = split_paths_and_messages(calls('git commit -m "normal bugfix"')[0][1])
    check("clean msg no hit", not dl.search(m2[0]))
    _, m3 = split_paths_and_messages(calls('git commit --message="Co-Authored-By: Claude"')[0][1])
    check("joined --message= extracted", bool(m3 and dl.search(m3[0])))
    # commit naming a managed path
    p4, _ = split_paths_and_messages(calls('git commit -m "x" CLAUDE.md')[0][1])
    check("commit managed path flagged", any(is_managed(x, globs) for x in p4))
    # branch model
    check("version/ create flagged",
          created_branch_name("switch", tokenize("-c version/9.9 dev")[0:]) == "version/9.9"
          or created_branch_name(*calls("git switch -c version/9.9 dev")[0]) == "version/9.9")
    check("checkout -b version flagged",
          created_branch_name(*calls("git checkout -b version/9.9")[0]) == "version/9.9")
    check("ordinary feature branch ok",
          not (created_branch_name(*calls("git switch -c feature/login")[0]) or "").startswith("version/"))
    check("branch -d not a create",
          created_branch_name(*calls("git branch -d old")[0]) is None)

    print("\n" + ("PASS" if not fails else f"{fails} FAILED"))
    return 1 if fails else 0


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--self-test":
        sys.exit(_self_test())
    main()
