#!/usr/bin/env python3
"""stealth_scrub.py — Stealth Mode hygiene + branch-reconciliation helper (v3.0).

Two deterministic, stdlib-only checks used while Stealth Mode is active
(`stealth-mode.value == "on"` in .claude/grimoire-config.json):

  scan      Scan committed DELIVERABLE content for AI/agent tells (the
            comment/commit-message hygiene deny-list). Defaults to the staged
            diff (`git diff --cached`); pass file paths to scan whole files.
            Grimoire's own concealed (managed) paths are skipped — they are
            never committed in stealth, so they cannot leak.

  branches  Track branches so no net-new branch Grimoire created survives the
            session. `--baseline` snapshots the current local branches to
            .claude/cache/stealth-branch-baseline.json; without it, the current
            branches are diffed against that baseline and the NET-NEW branches
            (present now, absent at baseline) are listed for reconciliation.

Read-only except `branches --baseline` (writes the cache snapshot).
Report-only unless `--strict` (non-zero exit on findings / net-new branches).

Usage:
  stealth_scrub.py scan [--staged] [--strict] [PATH ...]
  stealth_scrub.py branches [--baseline] [--strict]
  stealth_scrub.py --self-test
"""
import json
import os
import re
import subprocess
import sys

# ── Deny-list ────────────────────────────────────────────────────────────
# Tells that must never appear in committed deliverable content / messages.
# Short or ambiguous tokens use word boundaries so "ai" does not match
# "maintain"/"detail" and "llm" does not match inside an identifier. Multi-word
# phrases match the phrase with flexible internal whitespace.
_WORD_TOKENS = [
    "claude", "anthropic", "openai", "gpt", "copilot", "llm",
    "ai-generated", "ai generated", "assistant-generated",
]
_PHRASES = [
    r"generated by ai", r"language model", r"co-authored-by",
    r"as an ai", r"i'm an ai", r"i am an ai",
]
_LITERALS = ["🤖"]  # matched as plain substrings, no word boundary


def build_pattern(extra=None):
    """Compile one case-insensitive regex matching any deny-list entry.

    `extra` (from stealth-mode.comment-denylist) is treated as word tokens.
    """
    parts = []
    for tok in _WORD_TOKENS + list(extra or []):
        # \b is unreliable next to non-word chars like '-', so anchor on
        # non-alphanumeric (or string edge) around the token instead.
        esc = re.escape(tok)
        parts.append(rf"(?<![A-Za-z0-9]){esc}(?![A-Za-z0-9])")
    for ph in _PHRASES:
        parts.append(ph.replace(" ", r"\s+"))
    for lit in _LITERALS:
        parts.append(re.escape(lit))
    return re.compile("|".join(parts), re.IGNORECASE)


# ── Managed-path skip set (Grimoire's own concealed files) ──────────────────
MANAGED_PREFIXES = (
    ".claude/", "CLAUDE.md", "AGENTS.md",
    "docs/design/", "docs/grimoire/", "docs/roadmap.md", "docs/version-history.md",
    "docs/release-planning-v", "docs/release-planning/", "docs/grimoire/integration-workflow.md",
    "docs/coding-standards", "docs/architecture-guidelines.md",
    ".github/prompts/", ".github/copilot-instructions.md",
)
# docs/grimoire/ (v3.39 "Bulkhead"): the framework-internal doc tier — relocated
# framework design specs (docs/grimoire/design/) + study artifacts + the tier
# index. Managed Grimoire docs, so Stealth Mode must still recognize them.


def is_managed(path):
    p = path[2:] if path.startswith("./") else path
    p = p.lstrip("/")  # strip leading slashes only, never the dot of ".claude"
    return any(p == m or p.startswith(m) for m in MANAGED_PREFIXES)


def load_extra_denylist():
    try:
        cfg = json.load(open(".claude/grimoire-config.json"))
        return cfg.get("stealth-mode", {}).get("comment-denylist", []) or []
    except Exception:
        return []


def git(args):
    try:
        out = subprocess.run(["git"] + args, capture_output=True, text=True, timeout=15)
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0:
        return None
    return out.stdout


# ── scan ────────────────────────────────────────────────────────────────
def scan_staged(pat):
    """Yield (file, lineno-or-None, matched, line) over added staged lines."""
    diff = git(["diff", "--cached", "--unified=0", "--no-color"])
    if diff is None:
        return
    cur = None
    for raw in diff.splitlines():
        if raw.startswith("+++ "):
            cur = raw[6:] if raw.startswith("+++ b/") else raw[4:]
            continue
        if raw.startswith("+") and not raw.startswith("+++"):
            if cur and is_managed(cur):
                continue
            line = raw[1:]
            m = pat.search(line)
            if m:
                yield cur or "(staged)", None, m.group(0), line.strip()


def scan_files(pat, paths):
    for path in paths:
        if is_managed(path) or not os.path.isfile(path):
            continue
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                for n, line in enumerate(fh, 1):
                    m = pat.search(line)
                    if m:
                        yield path, n, m.group(0), line.strip()
        except OSError:
            continue


def cmd_scan(args):
    strict = "--strict" in args
    staged = "--staged" in args or not [a for a in args if not a.startswith("-")]
    paths = [a for a in args if not a.startswith("-")]
    pat = build_pattern(load_extra_denylist())
    findings = list(scan_files(pat, paths) if paths else scan_staged(pat))
    for f, n, tok, line in findings:
        loc = f"{f}:{n}" if n else f
        print(f"  - {loc}: tell {tok!r} in: {line[:100]}")
    where = "files" if paths else "staged diff"
    print(f"\nstealth-scrub scan: {len(findings)} tell(s) in {where}.")
    if strict and findings:
        sys.exit(1)


# ── branches ──────────────────────────────────────────────────────────────
BASELINE = ".claude/cache/stealth-branch-baseline.json"


def local_branches():
    out = git(["branch", "--format=%(refname:short)"])
    if out is None:
        return []
    return [b.strip() for b in out.splitlines() if b.strip()]


def cmd_branches(args):
    strict = "--strict" in args
    branches = local_branches()
    if "--baseline" in args:
        os.makedirs(os.path.dirname(BASELINE), exist_ok=True)
        json.dump(sorted(branches), open(BASELINE, "w"), indent=2)
        print(f"stealth-scrub: baseline snapshot wrote {len(branches)} branch(es) → {BASELINE}")
        return
    try:
        base = set(json.load(open(BASELINE)))
    except Exception:
        print(f"stealth-scrub: no baseline at {BASELINE} — run `branches --baseline` "
              "at session start first.")
        sys.exit(1 if strict else 0)
    net_new = sorted(set(branches) - base)
    for b in net_new:
        print(f"  - {b}  (created this session — reconcile + delete before session end)")
    print(f"\nstealth-scrub branches: {len(net_new)} net-new branch(es) to reconcile.")
    if strict and net_new:
        sys.exit(1)


# ── self-test ──────────────────────────────────────────────────────────────
def _self_test():
    pat = build_pattern(["acmecorp"])
    must_hit = [
        "// generated by Claude", "Co-Authored-By: Claude <x>", "this uses an LLM",
        "ai-generated helper", "language  model output", "see acmecorp wiki",
        "fix with 🤖", "as an AI assistant", "powered by GPT",
    ]
    must_miss = [
        "maintain the detail and claim", "retail email aircraft",  # no bare 'ai'
        "llmx_var = 1; gptr = 2",   # bounded: trailing alnum blocks the match
        "a normal comment about parsing", "https://example.com/path",
    ]
    fails = 0
    for s in must_hit:
        if not pat.search(s):
            print(f"FAIL (should hit): {s!r}"); fails += 1
    for s in must_miss:
        m = pat.search(s)
        if m:
            print(f"FAIL (should miss): {s!r} matched {m.group(0)!r}"); fails += 1
    print("ok" if not fails else f"{fails} FAILED")
    return 1 if fails else 0


def main():
    args = sys.argv[1:]
    if not args:
        print(__doc__); sys.exit(2)
    if args[0] == "--self-test":
        sys.exit(_self_test())
    sub, rest = args[0], args[1:]
    if sub == "scan":
        cmd_scan(rest)
    elif sub == "branches":
        cmd_branches(rest)
    else:
        print(__doc__); sys.exit(2)


if __name__ == "__main__":
    main()
